### ISSUE TITLE
Adding to miner list on site btcz.roks

### ISSUE THREAD

**Issue by abakus1** [bitcoinz-sites/btcz.rocks#12]
Hello
Cab You add our pool ( Abacusmine) www.abakus.gemini.net.pl to pool list on btcz.rocks?
We have setting donation to btcz community 0.8% per block.

Bartek

**Comment by egyptianbman** [comment]
I'm replacing the pool list on the site with a link to the forum page -- https://forum.btcz.rocks/t/pools-that-love-the-bitcoinz-community/51

Your pool is on there; thanks!
