### ISSUE TITLE
Btcz.rocks Bitcoin 2.0 header issue

### ISSUE THREAD

**Issue by xPeripheryx** [bitcoinz-sites/btcz.rocks#14]
I've had about 4 people talk to me about this specific issue already.

telegram] <Unklnoun> APP [1:22 AM] 
the main slogan on the page should explain everithing from the first look

Periphery - Join Mining On - pool.bitcoinzguiding.ovh [1:22 AM] 
yeah i agree
the page is a little underdeveloped

[telegram] <Unklnoun> APP [1:22 AM] 
in 3 sec ppl should get the point

[telegram] <Unklnoun> APP [1:23 AM] 
otherwise looks cheap

[telegram] <Unklnoun> APP [1:37 AM] 
How about this slogan.....Your Financial Freedom : BitcoinZ. 100% Decentralizied, Community Powered, Your Real Cryptocoin. (re @FairBTCZBot:[slack] <equipool.1ds.us> I told you they are available, for those who needs them)

**Comment by MrFishFingers** [comment]
So, what should the landing text say? "Your Financial Freedom : BitcoinZ. 100% Decentralizied, Community Powered, Your Real Cryptocoin"?

Get something specific and it could be changed. Maybe get marketing's help?

**Comment by xPeripheryx** [comment]
So, what should the landing text say? 

Your Communal Freedom : BitcoinZ. 
-Decentralized
-Community Powered & Driven
-POW-Equihash + zkSNARKs
-No Premine
-No ICO
-No Master Nodes
-No dev tax or fee

The decentralized champion we need.
True hero's play open source.
The land of financial freedom.

**Comment by egyptianbman** [comment]
That's quite a lot for the header. You need something that fits in the space allotted unless we want to change the whole layout.

![image](https://user-images.githubusercontent.com/323600/34621065-4f026e16-f20d-11e7-9cbe-0472333f68d1.png)

**Comment by xPeripheryx** [comment]
then it should just say this 
 
BitcoinZ
Communal Freedom

**Comment by xPeripheryx** [comment]
or 

BitcoinZ
Community Powered & Driven

**Comment by egyptianbman** [comment]
Has this been discussed in #marketing or is this your proposal? If not done so yet, please bring this up in #marketing as @MrFishFingers suggested then provide us with the final decision by the marketing team to implement.

Having the marketing team come up with this stuff then bringing it to the developers **after** doing so allows developers to keep chugging on other important issues while decisions about content are being made.

**Comment by xPeripheryx** [comment]
yeah it saying its your coin doesnt really scream this is a cool coin to me

**Comment by egyptianbman** [comment]
Let's get a decision rolling for the header. Please use https://goo.gl/forms/KeJn5XiM5T9WPmwC2 to make a selection or opt to keep it the same.

**Comment by egyptianbman** [comment]
Only received two votes, I don't think there's much interest in changing this at this time. Please create a new issue if the need arises in the future; thanks!
