### ISSUE TITLE
No team member information or pictures?

### ISSUE THREAD

**Issue by xPeripheryx** [bitcoinz-sites/btcz.rocks#15]
How do people know if this is a real project when you cant see physical people on the website? lol

On that note i've had several people inquire about this to me already in the last month.

**Comment by MrFishFingers** [comment]
Having contributors' pictures on a website doesn't magically validate a project, but to the point.

Work involved _before_ any development:
- [ ] Gather team members' picture and small bios. What do you do for people who want to stay anonymous?
- [ ] Figure how this is maintained. How is activity determined? List everyone who has ever contributed?

I think a "Contributors" page makes more sense, maybe linking to linkedin or github. That can be done for https://bitcoinzguiding.ovh/team.html too but it still requires someone to gather that information.
