### ISSUE TITLE
EXCH. Logo update

### ISSUE THREAD

**Issue by ihyatafsir** [bitcoinz-sites/btcz.rocks#33]
Graviex  - https://m.imgur.com/lLE6iEW?r
https://graviex.net/markets/btczbtc
Btc-alpha - https://goo.gl/images/Dj3TZw
https://btc-alpha.com/exchange/BTCZ_BTC/
Barterdex - https://99designs.ch/logo-design/contests/barterdex-logo-773509
 https://github.com/KomodoPlatform/BarterDEX/releases

**Comment by egyptianbman** [comment]
This is now included in the upcoming rewrite.
