### ISSUE TITLE
CSS change for replace Capital BITCOINZ  to BitcoinZ

### ISSUE THREAD

**Issue by ihyatafsir** [bitcoinz-sites/btcz.rocks#43]
CSS update for change Capital BITCOINZ  to BitcoinZ

**Comment by gilardh** [comment]
This request is still relevant?
If YES can you explain to me what it is.
Should we replace all the names 'BITCOINZ' with 'BitcoinZ' on the whole site?

**Comment by egyptianbman** [comment]
I don't think there's an issue. BitcoinZ is all caps in headers and non caps in normal text.
