### ISSUE TITLE
crex24 xchange logo

### ISSUE THREAD

**Issue by ihyatafsir** [bitcoinz-sites/btcz.rocks#52]
https://www.google.ch/search?q=crex24+logo&tbm=isch&source=iu&ictx=1&fir=g0qJc-csa-uH_M%253A%252CHIh2DVe6urCGjM%252C_&usg=__d_u36mp7toXuVxyncrdeCwFL28M%3D&sa=X&ved=0ahUKEwjh4vv88KHaAhURDuwKHYm5DOYQ9QEIMjAD#imgrc=g0qJc-csa-uH_M:

https://crex24.com/de/exchange/BTCZ-BTC

**Comment by gilardh** [comment]
I do not know what to do in this issue.
The logo and the link are correct on the website.

If everything is OK, I propose to close this request.

**Comment by gilardh** [comment]
![20181211 crex24](https://user-images.githubusercontent.com/39105646/49768781-cbaec280-fcdd-11e8-99b5-a9f6afd3658d.jpg)
