### ISSUE TITLE
octaex    and crex24 logo   

### ISSUE THREAD

**Issue by ihyatafsir** [bitcoinz-sites/btcz.rocks#53]
https://scontent-sea1-1.cdninstagram.com/vp/18b4f28d8c440b2d9e3b3189ff0180a2/5B3F03F3/t51.2885-15/e35/28154598_2042622849316206_3737147195682455552_n.jpg?ig_cache_key=MTcyNDYyNDg2NTA4MzY0OTkwMg%3D%3D.2

https://crex24.com/de/exchange/BTCZ-BTC

https://www.forexbrokerz.com/files/1522062537OctaEx%20logo.jpg
https://octaex.com/trade/index/market/btcz_btc/

**Comment by gilardh** [comment]
Hello,

The website https://octaex.com/trade/index/market/btcz_btc/ and https://octaex.com is down.
![20181211 octaex](https://user-images.githubusercontent.com/39105646/49769125-53490100-fcdf-11e8-8462-e28afeed13fc.jpg)

For me the logo and link of crex24 is correct.

If you are OK, this issue can be closed.
