### ISSUE TITLE
add a couple of items to nav menu / other

### ISSUE THREAD

**Issue by cryptorex** [bitcoinz-sites/btcz.rocks#7]
proposal to add 'Start Mining' with a link to our YouTube video showing how to use our GUI miner. https://youtu.be/RI-V7n8amFk

proposal to add 'Guides' to top menu nav bar and link to http://bitcoinzguiding.ovh/

proposal to add link to 'Info Bulletin) https://info.btcz.rocks

proposal to add link to 'Btcz Fund' site https://btcz.fund

**Comment by egyptianbman** [comment]
If you don't mind, I'll add these to the English site since I plan to delete all the other variations and replace them with that -- with programmatic translation, not a fully copy of the site for each.

**Comment by cryptorex** [comment]
no, thats awesome
